# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc775f9334ef60e29f5687bba20332fb76315d502b1438e6f57e2daedc04d79ee21a722883d085e47819817be7dfba35e76be521143e0c651f30143556760cfa

test:
  secret_key_base: 0fa7c4385e63eba26cffe76357bf188bcf55242537aa49fd30c60710e7e90f902dc66849fc171a5b97b42df8d23900afbf2564c40565e05a4550d8ccf440b5fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
